#:schema node_modules/wrangler/config-schema.json
name = "jiediangeshi-worker"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "1b923a9be9a1425a8492c1ea39c215b7" }
]

[assets]
directory = "./public"
